### ISSUE TITLE
手机上标签过长时破坏布局

### ISSUE THREAD

**Issue by haojie06** [removeif/hexo-theme-amazing#12]
当tag过长的时候，手机上的布局会被破坏，如图
![image.png](https://i.loli.net/2020/04/04/WLYrh9su4T8Bne7.png)
另外还有一点点小问题就是感觉当前布局在手机上显示有点太窄了，对于偏窄一些的手机屏幕来说，阅读比较吃力。
![image.png](https://i.loli.net/2020/04/04/PQDKbf3d7nZLgxW.png)

**Comment by haojie06** [comment]
对于第一个问题，妥协一点的话可以把标签缩短/减少。但是第二个问题文章在手机上的显示个人感觉是太窄了点，代码框一开始也只能看见很少的一部分。以及文章信息采用现在这种显示方法也显示不全，打扰您啦。
![image.png](https://i.loli.net/2020/04/05/6uUgWqoAjJhVvkt.png)

**Comment by removeif** [comment]
第一个问题确实存在，后面想想重新摆放tag位置，现在这样确实放不了多少。第二个问题显示不全是什么意思？有部分不显示么？我看我这边是显示完了的。代码框是可以左右滑动的？真正实际中一般手机上也看的少，本来屏幕就小，不方便看博客这些发自我的iPhone------------------ 原始邮件 ------------------发件人: haojie06  <notifications@github.com>发送时间: 2020年4月5日 00:55收件人: removeif/hexo-theme-amazing <hexo-theme-amazing@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[removeif/hexo-theme-amazing] 手机上标签过长时破坏布局 (#12)
对于第一个问题，妥协一点的话可以把标签缩短/减少。但是第二个问题文章在手机上的显示个人感觉是太窄了点，代码框一开始也只能看见很少的一部分。以及文章信息采用现在这种显示方法也显示不全，打扰您啦。


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/removeif/hexo-theme-amazing/issues/12#issuecomment-609057548",
"url": "https://github.com/removeif/hexo-theme-amazing/issues/12#issuecomment-609057548",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by haojie06** [comment]
显示不全指的是下面这一栏，在手机上显示不完整，因为不够长(图片是从电脑上截图的，可以和之前的图片对比一下)，然后如果我想让各个栏目在手机上显示得宽一点点该怎么改呢。
![image.png](https://i.loli.net/2020/04/05/6uUgWqoAjJhVvkt.png)

**Comment by removeif** [comment]
第一个也是可以左右滑动的第二个审查页面上元素，然后找到对应的css节点，去对应源码中css文件相应改发自我的iPhone------------------ 原始邮件 ------------------发件人: haojie06  <notifications@github.com>发送时间: 2020年4月5日 09:48收件人: removeif/hexo-theme-amazing <hexo-theme-amazing@noreply.github.com>抄送: 辣椒の酱 <removeif@163.com>, Comment <comment@noreply.github.com>主题: 回复：[removeif/hexo-theme-amazing] 手机上标签过长时破坏布局 (#12)
显示不全指的是下面这一栏，在手机上显示不完整，因为不够长(图片是从电脑上截图的，可以和之前的图片对比一下)，然后如果我想让各个栏目在手机上显示得宽一点点该怎么改呢。


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/removeif/hexo-theme-amazing/issues/12#issuecomment-609115445",
"url": "https://github.com/removeif/hexo-theme-amazing/issues/12#issuecomment-609115445",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by haojie06** [comment]
好吧，谢谢，我就是感觉这些信息左右滑动有点不太好，不过也不是很大的问题， 打扰了

**Comment by haojie06** [comment]
新的标签布局可以只在手机上启用吗，之前的标签摆放方式在电脑上还是比较正常的，如果采用新的布局感觉占用的位置多了一些，显得有些空了。

**Comment by removeif** [comment]
新布局手机上电脑上都还好吧，之前布局tag多几个就不行了发自我的iPhone------------------ 原始邮件 ------------------发件人: haojie06  <notifications@github.com>发送时间: 2020年4月6日 14:30收件人: removeif/hexo-theme-amazing <hexo-theme-amazing@noreply.github.com>抄送: 辣椒の酱 <removeif@163.com>, Comment <comment@noreply.github.com>主题: 回复：[removeif/hexo-theme-amazing] 手机上标签过长时破坏布局 (#12)
新的标签布局可以只在手机上启用吗，之前的标签摆放方式在电脑上还是比较正常的，如果采用新的布局感觉占用的位置多了一些，显得有些空了。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/removeif/hexo-theme-amazing/issues/12#issuecomment-609591379",
"url": "https://github.com/removeif/hexo-theme-amazing/issues/12#issuecomment-609591379",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by haojie06** [comment]
已经没问题了，我看了看我这布局占位置太多是因为cdn没有及时更新css造成的，现在好了。谢谢作者了
